version: '3'
services:
  my-form:
    image: my-frontend
    ports:
      - "8080:80"
    depends_on:
      - my-server

  my-server:
    image: my-backend:v.2
    volumes:
      - ./backend/database/user.json:/app/database/user.json
    ports:
      - "3000:3000"
