version: '3'
services:
  my-form:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - my-server

  my-server:
    build: ./backend
    volumes:
      - ./backend/database/user.json:/app/database/user.json
    ports:
      - "3000:3000"
