### GET All Arrays
GET http://localhost:3000/readAll HTTP/1.1

### GET Array By Name
GET http://localhost:3000/read/1 HTTP/1.1

### Create new Array
GET http://localhost:3000/create/songs HTTP/1.1

### Add Element to an array
POST http://localhost:3000/add/songs HTTP/1.1
Content-Type: application/json

{
    "element": "love Story"
}


### Update an element of an array
PUT http://localhost:3000/update/people HTTP/1.1
Content-Type: application/json

{
    "oldValue": "ali",
    "newValue": "nima"
}

### Delete an element from an array
DELETE http://localhost:3000/delete/fruits HTTP/1.1
Content-Type: application/json

{
    "element": "banana"
}